# models available: apertus-8b, apertus-70b, gpt-4o-mini, gpt-4o, DeepSeek-V3.1, Llamma-4-Scout, gpt-oss-120b
model_name: gpt-4o
teacher_model_name: apertus-8b

output_dir: data/privacy
tasks_filename: privacy_data.csv

num_correct_answers: 1
num_partial_answers: 1
num_incorrect_answers: 1

lm_temperature: 0.6
lm_cache: false
