# models: apertus-8b, apertus-70b, gpt-4o-mini, gpt-4o, DeepSeek-V3.1,
model_name: gpt-4o-mini
teacher_model_name: gpt-4o-mini

# Raw input folders (JSON)
raw_tasks_dir: data/raw/tasks
raw_chunks_dir: data/raw/chunks

# Synth output (CSV)
output_dir: data/synth
tasks_filename: tasks_unified.csv

num_correct_answers: 1
num_partial_answers: 1
num_incorrect_answers: 1

lm_temperature: 1.0
lm_temperature_creation: 1.4
lm_cache: false
