model_name: apertus-70b
teacher_model_name: gpt-4o-mini
output_dir: data/privacy
tasks_filename: privacy_data.csv

num_correct_answers: 1
num_partial_answers: 1
num_incorrect_answers: 1

lm_temperature: 0.6
lm_cache: false
